### ISSUE TITLE
Check and do attributions as per Spotify developer guidelines 

### ISSUE THREAD

**Issue by amogh2019** [amogh2019/bajte-reh-bas#2]
- [x] mention that it is just a template // which can used for reference purpose to become familiar with appsmith and Spotify web apis for development
- [x] You must not offer Audio Preview Clips as a standalone service or product.
VI https://developer.spotify.com/policy/#v-widgets-and-audio-preview-clips

- [x] ensure the app is not publically available in app smith and add how not to share

**Comment by AntiGhot** [comment]
working on it
